routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/login','App\Http\Controllers\Controller@getauthentica');
Route::post('/login','App\Http\Controllers\Controller@authentica')->name('postLogin');

Route::get('post','App\Http\Controllers\PageController@index');
Route::get('user','App\Http\Controllers\PageController@user');
Route::prefix('action')->group( function () {
    Route::name('action.')->group( function () {
        Route::get('/edit/{id}', 'App\Http\Controllers\PageController@edit')->name('edit');
        Route::put('/update/{id}', 'App\Http\Controllers\PageController@update')->name('update');
        Route::get('/delete/{id}', 'App\Http\Controllers\PageController@destroy')->name('destroy');
        Route::get('/create', 'App\Http\Controllers\PageController@create')->name('create');
        Route::post('/create', 'App\Http\Controllers\PageController@store')->name('store');
        Route::get('laravel-send-email', 'App\Http\Controllers\EmailController@sendEMail')->name('email');

    });
});
Route::get('pdfview',array('as'=>'pdfview','uses'=>'App\Http\Controllers\BestInterviewQuestionController@pdfview'));

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $table = 'posts';
    protected $fillable = [
        'id','user_id','title','status','description',
    ];
    public function user ()
    {
        return $this->belongsTo('App\Models\User','user_id');

    }
    public $timestamps = false;


}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'users';
    protected $fillable = [
        'name',
        'email',
        'password',
    ];
    public function posts ()
    {
        return $this->hasMany('App\Models\Post','user_id');
    }
//    public $timestamps = false;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public $timestamps = false;

}

app/Http/Controllers/BestInterviewQuestionController.php
<?php

namespace App\Http\Controllers;

use Barryvdh\DomPDF\PDF;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BestInterviewQuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function pdfview(Request $request)
    {
        $post = DB::table("posts")->get();
        view()->share('post',$post);
        if($request->has('download')){
            $pdf = PDF::loadView('pdfview');
            return $pdf->download('pdfview.pdf');
        }
        return view('action.pdfview');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Support\Facades\Auth;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    public function authentica(Request $request)
    {
        $credentials = $request->only('email', 'password');
        if (Auth::attempt($credentials)) {
            return redirect()->intended('/post');
        }else{
            return redirect()->back()->with('message',"nhap lai");
        }
    }
    public function getauthentica()
    {
        return view ('auth.login');
    }
}

app/Http/Controllers/EmailController.php
<?php

namespace App\Http\Controllers;

use App\Mail\MailNotify;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class EmailController extends Controller
{
    public  function sendEmai()
    {
        $user = auth()->user();
        $emails = ['myoneemail@esomething.com', 'myother@esomething.com','myother2@esomething.com'];

        Mail::send('emails.welcome', [], function($message) use ($emails)
        {
            $message->to($emails)->subject('This is test e-mail');
        });
        var_dump( Mail:: failures());
        exit;
    }
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;

class PageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function user()
    {
        $users = User::with('posts')->orderByDesc('id')->get();
        dd($users);
    }
    public function index()
    {
        $posts = Post::with('user')->orderByDesc('id')->get();
        return view('public.home',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = Post::with('user')->get();
        $users = User::all();
        return view('action.create',compact('post','users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $post = new Post($data);
        $post ->save();

        $post = Post::with('user')->get();
        $users = User::all();
        return redirect('/post')->with([
            'post'=> $post,
            'users' => $users,
        ]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('action.editpost',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        $user = User::with('posts')->get();
        $post = Post::findOrFail($id);
        $post ->update($request->all());
//        dd($post);
        return redirect('/post');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();
        return redirect()->back();
    }
}

resources/views/action/create.blade.php
@extends('layouts.app')
@section('title', 'Tao san pham moi')
@section('content')
    <h1>Tao san pham moi</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <form method="post" action="{{ route('action.store') }}">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Checkbox</label>
            <input type="text" id="checkbox" name="status">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Title</label>
            <input type="text" name="title" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER TITLE">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Description</label>
            <input type="text" name="description" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER DESCRIPTION">
        </div>
        <div class="form-group">
            <select name="user_id" class="form-control">
                @forelse($users as $users)
                    <option value="{{ $users->id }}">{{ $users->name }}</option>
                @empty
                    <option>No data</option>
                @endforelse
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Tao moi</button>
    </form>
@stop

resources/views/action/editpost.blade.php
@extends('layouts.app')
@section('title', 'Edit the loai')
@section('content')
    <h1>Edit Post</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <form method="post" action="{{ route('action.update', ['id' => $post->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" value="{{$post->name}}" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Title</label>
            <input type="text" value="{{$post->title}}" name="title" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Description</label>
            <input type="text" value="{{$post->description}}" name="description" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="text" value="{{$post->user->name}}" name="email" class="form-control"  aria-describedby="emailHelp" placeholder="ENTER NAME">
        </div>

        <button type="submit" class="btn btn-primary">Cap nhat</button>
    </form>
@stop

resources/views/action/email.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel Send Email Example</title>
</head>
<body>

<h1>This is test mail from ABC</h1>
<p>Thank you, {{ $user->name }}</p>

</body>
</html>

resources/views/action/pdfview.blade.php
@extends('layouts.app')


<div class="container">
    <a href="{{ route('pdfview',['download'=>'pdf']) }}">Download PDF</a>
    <table>

        <div class="row">
            <div class="col-md-4">No</div>
            <div class="col-md-4">Title</div>
            <div class="col-md-4">Description</div>
        </div>
        @foreach ($post as $key => $post)
            <div class="row">
                <div class="col-md-4">{{ ++$key }}</div>
                <div class="col-md-4">{{ $post->title }}</div>
                <div class="col-md-4">{{$post->description }}</div>
            </div>
        @endforeach
    </table>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{asset('css/data.css')}}">
</head>
<body>


@yield('content')


</body>
</html>